{{- if .Values.serviceAccount }}
{{- $serviceAccount := .Values.serviceAccount | default dict }}
{{- $name := $serviceAccount.name | default dict }}
{{- $roleArn := $serviceAccount.roleArn | default dict }}

{{- if .Values.serviceAccount.enabled | default "false" | eq "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  annotations:
    "eks.amazonaws.com/role-arn": {{ $roleArn }}
{{- end }}
{{- end }}
