{{- if .Values.ingress }}
{{- $ingress := .Values.ingress | default dict }}
{{- $annotations := $ingress.annotations | default dict }}
{{- $acm := $annotations.acm | default dict }}
{{- $groupOrder := $annotations.order | default 1 }}
{{- $scheme := $annotations.scheme | default "internet-facing" }}
{{ $environment := .Values.environment | default "none" }}

{{ $ingress_name := $ingress.name | default $environment }}
{{ $targetType := $ingress.targetType | default "instance"}}


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    alb.ingress.kubernetes.io/group.name: {{ $ingress_name }}-ingress
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: {{ $ingress_name }}-applications
    alb.ingress.kubernetes.io/scheme: {{ $scheme }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: {{ $acm }}
    alb.ingress.kubernetes.io/group.order: {{ $groupOrder | quote}}
    alb.ingress.kubernetes.io/target-type: {{ $targetType }}
spec:
  ingressClassName: alb

  {{- if $ingress.rules }}
  {{- $rules := $ingress.rules | default dict }}
  rules:
    {{ range $rules }}
    - host: {{ .host }}
      http:
        paths:
          {{- if .http.paths }}
            {{ range .http.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
            {{end}}
          {{- end }}
    {{end}}
  {{- end }}
{{- end }}
