{{- if .Values.virtualService }}

{{- $virtualService := .Values.virtualService | default dict }}
{{- $target := $virtualService.target | default dict }}
{{- $hosts := $virtualService.hosts | default dict }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  {{- range $key, $value := $hosts }}
    - {{ $value | quote }}
  {{- end }}
  gateways:
    - orbit-gateway.istio-system
  http:
    - match:
        - headers:
            target:
              exact: {{ $target }}
      route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: 80

{{- end }}
