{{- $application_type := "micro-services" }}
{{ $volumes := .Values.volumes | default nil }}
{{- $csiSecrets := .Values.csiSecrets | default dict }}
{{- $csiSecretsEnabled := $csiSecrets.enabled | default nil }}
{{- $serviceAccountName := $csiSecrets.serviceAccountName | default "application-permission" }}
{{- $module := .Values.module | default "none" }}
{{- $terminationGracePeriodSeconds := .Values.terminationGracePeriodSeconds | default 60 }}
{{ $environment := .Values.environment | default "none" }}
{{ $namespace := .Release.Namespace | default "none" }}

apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ .Release.Name }}
  labels:
    orbit_application_name: {{ .Release.Name }}
    orbit_application_type: {{ $application_type }}
    orbit_module: {{ $module }}
    "sidecar.istio.io/inject": "false"
spec:
  pollingInterval: {{ .Values.keda.pollingInterval }}
  successfulJobsHistoryLimit: {{ .Values.keda.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.keda.failedJobsHistoryLimit }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}

  jobTargetRef:
    parallelism: 1
    completions: 1
    {{- if .Values.keda.activeDeadlineSeconds }}
    activeDeadlineSeconds: {{ .Values.keda.activeDeadlineSeconds }}
    {{- end }}
    template:
      metadata:
        labels:
          sidecar.istio.io/inject: "false"
      spec:
        {{- if $csiSecretsEnabled }}
        serviceAccountName: {{ $serviceAccountName }}
        {{- end }}
        {{- if .Values.nodeSelector }}
        nodeSelector:
          {{- range $key, $value := .Values.nodeSelector }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.affinity }}
        affinity:
          {{- toYaml .Values.affinity | nindent 8 }}
        {{- end }}

        terminationGracePeriodSeconds: {{ $terminationGracePeriodSeconds }}

        volumes:
        {{- if $csiSecretsEnabled }}
          - name: secrets-store-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: {{ .Release.Name }}
        {{- end }}


        {{- if $volumes }}
          {{- range $volume := $volumes }}
          - name: {{ $volume.name }}
            {{- if $volume.claimName }}
            persistentVolumeClaim:
              claimName: {{ $volume.claimName }}
            {{- else }}
            emptyDir: { }
            {{- end }}
          {{- end }}
        {{- end }}

        containers:
          {{- range .Values.containers }}
          - name: {{ .name | default "default" }}
            imagePullPolicy: IfNotPresent
            image: {{ .repository.image }}:{{ .repository.tag }}

            {{- if .lifecycle }}
            lifecycle:
              {{- toYaml .lifecycle | nindent 14 }}
            {{- end }}

            env:
            {{- range $key, $value := .environments }}
              - name: {{ $key }}
                value: {{ $value | quote }}
            {{- end }}
              - name: ENVIRONMENT
                value: {{ $environment }}
              - name: NAMESPACE
                value: {{ $namespace }}

            {{- $resources := .resources | default dict }}
            {{- $requests := $resources.requests | default dict }}
            {{- $limits := $resources.limits | default dict }}
            resources:
              requests:
                cpu: {{ $requests.cpu | default "100m" }}
                memory: {{ $requests.memory | default "32Mi" }}
              limits:
                cpu: {{ $limits.cpu | default "200m" }}
                memory: {{ $limits.memory | default "128Mi" }}

            volumeMounts:
            {{- if $csiSecretsEnabled }}
              - name: secrets-store-inline
                mountPath: "/mnt/secrets-store"
                readOnly: true
            {{- end }}
            {{- if $volumes }}
              {{- range $volume := $volumes }}
              - mountPath: {{ $volume.mountPath }}
                name: {{ $volume.name }}
              {{- end }}
            {{- end }}
          {{- end }}
