{{- if .Values.volumes }}
{{ range $volume := .Values.volumes }}
{{- if $volume.claimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: {{ $volume.claimName }}
  name: {{ $volume.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.size }}
  storageClassName: gp3
{{ end }}
{{- end }}
{{- end }}
