name: Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  terraform-init:
    name: init
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_region: us-east-1
      TF_VAR_bucket_name: "${{ vars.CHART_HELM_BUCKET_ENV }}"
    permissions:
      id-token: write
      contents: read
    steps:   
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'
    
      - uses: hashicorp/setup-terraform@v3
        name: setup
        with:
            terraform_version: "1.5.0"
    
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER_ENV }}:role/github-actions-${{ vars.ENVIRONMENT }}
          role-session-name: github-actions-${{ vars.ENVIRONMENT }}
          aws-region: 'us-east-1'

      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Terraform Init
        run: |
          terraform init -backend-config=bucket=${{ vars.TERRAFORM_BUCKET }} -backend-config=key=${{ github.event.repository.name }}/terraform.tfstate -backend-config=region=us-east-1

      - name: Terraform Plan
        run: |
          terraform plan -no-color

      - name: Terraform Apply
        run: |
          terraform apply -no-color -auto-approve



